// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.3
// source: eas_api/v1/eas.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EasServiceClient is the client API for EasService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EasServiceClient interface {
	// 登录
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// ===============================用户模块=========================================
	// 创建用户
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	// 用户列表
	GetPageList(ctx context.Context, in *GetPageListRequest, opts ...grpc.CallOption) (*GetPageListResponse, error)
	// 用户详情
	GetUserDetail(ctx context.Context, in *GetUserDetailRequest, opts ...grpc.CallOption) (*GetUserDetailResponse, error)
	// 查询用户个人信息
	GetUserSelfDetail(ctx context.Context, in *GetUserSelfDetailRequest, opts ...grpc.CallOption) (*GetUserSelfDetailResponse, error)
	// 禁用/启用用户
	SetUserStatus(ctx context.Context, in *SetUserStatusRequest, opts ...grpc.CallOption) (*SetUserStatusResponse, error)
	// 修改用户信息
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	// 修改用户个人信息
	UpdateUserSelf(ctx context.Context, in *UpdateUserSelfRequest, opts ...grpc.CallOption) (*UpdateUserSelfResponse, error)
	// 重置用户密码
	ResetUserPassWord(ctx context.Context, in *ResetUserPassWordRequest, opts ...grpc.CallOption) (*ResetUserPassWordResponse, error)
	// 修改密码
	UpdateUserPassWord(ctx context.Context, in *UpdateUserPassWordRequest, opts ...grpc.CallOption) (*UpdateUserPassWordResponse, error)
	// 删除
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
	// ===============================试卷模块=========================================
	// 创建试卷
	CreateSalesPaper(ctx context.Context, in *CreateSalesPaperRequest, opts ...grpc.CallOption) (*CreateSalesPaperResponse, error)
	// 试卷列表
	GetSalesPaperPageList(ctx context.Context, in *GetSalesPaperPageListRequest, opts ...grpc.CallOption) (*GetSalesPaperPageListResponse, error)
	// 可用试卷列表
	GetUsableSalesPaperPageList(ctx context.Context, in *GetUsableSalesPaperPageListRequest, opts ...grpc.CallOption) (*GetUsableSalesPaperPageListResponse, error)
	// 试卷详情
	GetSalesPaperDetail(ctx context.Context, in *GetSalesPaperDetailRequest, opts ...grpc.CallOption) (*GetSalesPaperDetailResponse, error)
	// 修改试卷信息
	UpdateSalesPaper(ctx context.Context, in *UpdateSalesPaperRequest, opts ...grpc.CallOption) (*UpdateSalesPaperResponse, error)
	// 禁用/启用试卷
	SetSalesPaperStatus(ctx context.Context, in *SetSalesPaperStatusRequest, opts ...grpc.CallOption) (*SetSalesPaperStatusResponse, error)
	// 删除试卷
	DeleteSalesPaper(ctx context.Context, in *DeleteSalesPaperRequest, opts ...grpc.CallOption) (*DeleteSalesPaperResponse, error)
}

type easServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEasServiceClient(cc grpc.ClientConnInterface) EasServiceClient {
	return &easServiceClient{cc}
}

func (c *easServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/eas_api.v1.EasService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *easServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/eas_api.v1.EasService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *easServiceClient) GetPageList(ctx context.Context, in *GetPageListRequest, opts ...grpc.CallOption) (*GetPageListResponse, error) {
	out := new(GetPageListResponse)
	err := c.cc.Invoke(ctx, "/eas_api.v1.EasService/GetPageList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *easServiceClient) GetUserDetail(ctx context.Context, in *GetUserDetailRequest, opts ...grpc.CallOption) (*GetUserDetailResponse, error) {
	out := new(GetUserDetailResponse)
	err := c.cc.Invoke(ctx, "/eas_api.v1.EasService/GetUserDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *easServiceClient) GetUserSelfDetail(ctx context.Context, in *GetUserSelfDetailRequest, opts ...grpc.CallOption) (*GetUserSelfDetailResponse, error) {
	out := new(GetUserSelfDetailResponse)
	err := c.cc.Invoke(ctx, "/eas_api.v1.EasService/GetUserSelfDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *easServiceClient) SetUserStatus(ctx context.Context, in *SetUserStatusRequest, opts ...grpc.CallOption) (*SetUserStatusResponse, error) {
	out := new(SetUserStatusResponse)
	err := c.cc.Invoke(ctx, "/eas_api.v1.EasService/SetUserStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *easServiceClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	out := new(UpdateUserResponse)
	err := c.cc.Invoke(ctx, "/eas_api.v1.EasService/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *easServiceClient) UpdateUserSelf(ctx context.Context, in *UpdateUserSelfRequest, opts ...grpc.CallOption) (*UpdateUserSelfResponse, error) {
	out := new(UpdateUserSelfResponse)
	err := c.cc.Invoke(ctx, "/eas_api.v1.EasService/UpdateUserSelf", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *easServiceClient) ResetUserPassWord(ctx context.Context, in *ResetUserPassWordRequest, opts ...grpc.CallOption) (*ResetUserPassWordResponse, error) {
	out := new(ResetUserPassWordResponse)
	err := c.cc.Invoke(ctx, "/eas_api.v1.EasService/ResetUserPassWord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *easServiceClient) UpdateUserPassWord(ctx context.Context, in *UpdateUserPassWordRequest, opts ...grpc.CallOption) (*UpdateUserPassWordResponse, error) {
	out := new(UpdateUserPassWordResponse)
	err := c.cc.Invoke(ctx, "/eas_api.v1.EasService/UpdateUserPassWord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *easServiceClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	out := new(DeleteUserResponse)
	err := c.cc.Invoke(ctx, "/eas_api.v1.EasService/DeleteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *easServiceClient) CreateSalesPaper(ctx context.Context, in *CreateSalesPaperRequest, opts ...grpc.CallOption) (*CreateSalesPaperResponse, error) {
	out := new(CreateSalesPaperResponse)
	err := c.cc.Invoke(ctx, "/eas_api.v1.EasService/CreateSalesPaper", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *easServiceClient) GetSalesPaperPageList(ctx context.Context, in *GetSalesPaperPageListRequest, opts ...grpc.CallOption) (*GetSalesPaperPageListResponse, error) {
	out := new(GetSalesPaperPageListResponse)
	err := c.cc.Invoke(ctx, "/eas_api.v1.EasService/GetSalesPaperPageList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *easServiceClient) GetUsableSalesPaperPageList(ctx context.Context, in *GetUsableSalesPaperPageListRequest, opts ...grpc.CallOption) (*GetUsableSalesPaperPageListResponse, error) {
	out := new(GetUsableSalesPaperPageListResponse)
	err := c.cc.Invoke(ctx, "/eas_api.v1.EasService/GetUsableSalesPaperPageList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *easServiceClient) GetSalesPaperDetail(ctx context.Context, in *GetSalesPaperDetailRequest, opts ...grpc.CallOption) (*GetSalesPaperDetailResponse, error) {
	out := new(GetSalesPaperDetailResponse)
	err := c.cc.Invoke(ctx, "/eas_api.v1.EasService/GetSalesPaperDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *easServiceClient) UpdateSalesPaper(ctx context.Context, in *UpdateSalesPaperRequest, opts ...grpc.CallOption) (*UpdateSalesPaperResponse, error) {
	out := new(UpdateSalesPaperResponse)
	err := c.cc.Invoke(ctx, "/eas_api.v1.EasService/UpdateSalesPaper", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *easServiceClient) SetSalesPaperStatus(ctx context.Context, in *SetSalesPaperStatusRequest, opts ...grpc.CallOption) (*SetSalesPaperStatusResponse, error) {
	out := new(SetSalesPaperStatusResponse)
	err := c.cc.Invoke(ctx, "/eas_api.v1.EasService/SetSalesPaperStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *easServiceClient) DeleteSalesPaper(ctx context.Context, in *DeleteSalesPaperRequest, opts ...grpc.CallOption) (*DeleteSalesPaperResponse, error) {
	out := new(DeleteSalesPaperResponse)
	err := c.cc.Invoke(ctx, "/eas_api.v1.EasService/DeleteSalesPaper", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EasServiceServer is the server API for EasService service.
// All implementations must embed UnimplementedEasServiceServer
// for forward compatibility
type EasServiceServer interface {
	// 登录
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	// ===============================用户模块=========================================
	// 创建用户
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	// 用户列表
	GetPageList(context.Context, *GetPageListRequest) (*GetPageListResponse, error)
	// 用户详情
	GetUserDetail(context.Context, *GetUserDetailRequest) (*GetUserDetailResponse, error)
	// 查询用户个人信息
	GetUserSelfDetail(context.Context, *GetUserSelfDetailRequest) (*GetUserSelfDetailResponse, error)
	// 禁用/启用用户
	SetUserStatus(context.Context, *SetUserStatusRequest) (*SetUserStatusResponse, error)
	// 修改用户信息
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	// 修改用户个人信息
	UpdateUserSelf(context.Context, *UpdateUserSelfRequest) (*UpdateUserSelfResponse, error)
	// 重置用户密码
	ResetUserPassWord(context.Context, *ResetUserPassWordRequest) (*ResetUserPassWordResponse, error)
	// 修改密码
	UpdateUserPassWord(context.Context, *UpdateUserPassWordRequest) (*UpdateUserPassWordResponse, error)
	// 删除
	DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
	// ===============================试卷模块=========================================
	// 创建试卷
	CreateSalesPaper(context.Context, *CreateSalesPaperRequest) (*CreateSalesPaperResponse, error)
	// 试卷列表
	GetSalesPaperPageList(context.Context, *GetSalesPaperPageListRequest) (*GetSalesPaperPageListResponse, error)
	// 可用试卷列表
	GetUsableSalesPaperPageList(context.Context, *GetUsableSalesPaperPageListRequest) (*GetUsableSalesPaperPageListResponse, error)
	// 试卷详情
	GetSalesPaperDetail(context.Context, *GetSalesPaperDetailRequest) (*GetSalesPaperDetailResponse, error)
	// 修改试卷信息
	UpdateSalesPaper(context.Context, *UpdateSalesPaperRequest) (*UpdateSalesPaperResponse, error)
	// 禁用/启用试卷
	SetSalesPaperStatus(context.Context, *SetSalesPaperStatusRequest) (*SetSalesPaperStatusResponse, error)
	// 删除试卷
	DeleteSalesPaper(context.Context, *DeleteSalesPaperRequest) (*DeleteSalesPaperResponse, error)
	mustEmbedUnimplementedEasServiceServer()
}

// UnimplementedEasServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEasServiceServer struct {
}

func (UnimplementedEasServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedEasServiceServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedEasServiceServer) GetPageList(context.Context, *GetPageListRequest) (*GetPageListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPageList not implemented")
}
func (UnimplementedEasServiceServer) GetUserDetail(context.Context, *GetUserDetailRequest) (*GetUserDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserDetail not implemented")
}
func (UnimplementedEasServiceServer) GetUserSelfDetail(context.Context, *GetUserSelfDetailRequest) (*GetUserSelfDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserSelfDetail not implemented")
}
func (UnimplementedEasServiceServer) SetUserStatus(context.Context, *SetUserStatusRequest) (*SetUserStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetUserStatus not implemented")
}
func (UnimplementedEasServiceServer) UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedEasServiceServer) UpdateUserSelf(context.Context, *UpdateUserSelfRequest) (*UpdateUserSelfResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserSelf not implemented")
}
func (UnimplementedEasServiceServer) ResetUserPassWord(context.Context, *ResetUserPassWordRequest) (*ResetUserPassWordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetUserPassWord not implemented")
}
func (UnimplementedEasServiceServer) UpdateUserPassWord(context.Context, *UpdateUserPassWordRequest) (*UpdateUserPassWordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserPassWord not implemented")
}
func (UnimplementedEasServiceServer) DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUser not implemented")
}
func (UnimplementedEasServiceServer) CreateSalesPaper(context.Context, *CreateSalesPaperRequest) (*CreateSalesPaperResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSalesPaper not implemented")
}
func (UnimplementedEasServiceServer) GetSalesPaperPageList(context.Context, *GetSalesPaperPageListRequest) (*GetSalesPaperPageListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSalesPaperPageList not implemented")
}
func (UnimplementedEasServiceServer) GetUsableSalesPaperPageList(context.Context, *GetUsableSalesPaperPageListRequest) (*GetUsableSalesPaperPageListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsableSalesPaperPageList not implemented")
}
func (UnimplementedEasServiceServer) GetSalesPaperDetail(context.Context, *GetSalesPaperDetailRequest) (*GetSalesPaperDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSalesPaperDetail not implemented")
}
func (UnimplementedEasServiceServer) UpdateSalesPaper(context.Context, *UpdateSalesPaperRequest) (*UpdateSalesPaperResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSalesPaper not implemented")
}
func (UnimplementedEasServiceServer) SetSalesPaperStatus(context.Context, *SetSalesPaperStatusRequest) (*SetSalesPaperStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetSalesPaperStatus not implemented")
}
func (UnimplementedEasServiceServer) DeleteSalesPaper(context.Context, *DeleteSalesPaperRequest) (*DeleteSalesPaperResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSalesPaper not implemented")
}
func (UnimplementedEasServiceServer) mustEmbedUnimplementedEasServiceServer() {}

// UnsafeEasServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EasServiceServer will
// result in compilation errors.
type UnsafeEasServiceServer interface {
	mustEmbedUnimplementedEasServiceServer()
}

func RegisterEasServiceServer(s grpc.ServiceRegistrar, srv EasServiceServer) {
	s.RegisterService(&EasService_ServiceDesc, srv)
}

func _EasService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EasServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eas_api.v1.EasService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EasServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EasService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EasServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eas_api.v1.EasService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EasServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EasService_GetPageList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPageListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EasServiceServer).GetPageList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eas_api.v1.EasService/GetPageList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EasServiceServer).GetPageList(ctx, req.(*GetPageListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EasService_GetUserDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EasServiceServer).GetUserDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eas_api.v1.EasService/GetUserDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EasServiceServer).GetUserDetail(ctx, req.(*GetUserDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EasService_GetUserSelfDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserSelfDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EasServiceServer).GetUserSelfDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eas_api.v1.EasService/GetUserSelfDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EasServiceServer).GetUserSelfDetail(ctx, req.(*GetUserSelfDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EasService_SetUserStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUserStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EasServiceServer).SetUserStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eas_api.v1.EasService/SetUserStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EasServiceServer).SetUserStatus(ctx, req.(*SetUserStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EasService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EasServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eas_api.v1.EasService/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EasServiceServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EasService_UpdateUserSelf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserSelfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EasServiceServer).UpdateUserSelf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eas_api.v1.EasService/UpdateUserSelf",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EasServiceServer).UpdateUserSelf(ctx, req.(*UpdateUserSelfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EasService_ResetUserPassWord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetUserPassWordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EasServiceServer).ResetUserPassWord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eas_api.v1.EasService/ResetUserPassWord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EasServiceServer).ResetUserPassWord(ctx, req.(*ResetUserPassWordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EasService_UpdateUserPassWord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserPassWordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EasServiceServer).UpdateUserPassWord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eas_api.v1.EasService/UpdateUserPassWord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EasServiceServer).UpdateUserPassWord(ctx, req.(*UpdateUserPassWordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EasService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EasServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eas_api.v1.EasService/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EasServiceServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EasService_CreateSalesPaper_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSalesPaperRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EasServiceServer).CreateSalesPaper(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eas_api.v1.EasService/CreateSalesPaper",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EasServiceServer).CreateSalesPaper(ctx, req.(*CreateSalesPaperRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EasService_GetSalesPaperPageList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSalesPaperPageListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EasServiceServer).GetSalesPaperPageList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eas_api.v1.EasService/GetSalesPaperPageList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EasServiceServer).GetSalesPaperPageList(ctx, req.(*GetSalesPaperPageListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EasService_GetUsableSalesPaperPageList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsableSalesPaperPageListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EasServiceServer).GetUsableSalesPaperPageList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eas_api.v1.EasService/GetUsableSalesPaperPageList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EasServiceServer).GetUsableSalesPaperPageList(ctx, req.(*GetUsableSalesPaperPageListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EasService_GetSalesPaperDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSalesPaperDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EasServiceServer).GetSalesPaperDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eas_api.v1.EasService/GetSalesPaperDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EasServiceServer).GetSalesPaperDetail(ctx, req.(*GetSalesPaperDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EasService_UpdateSalesPaper_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSalesPaperRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EasServiceServer).UpdateSalesPaper(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eas_api.v1.EasService/UpdateSalesPaper",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EasServiceServer).UpdateSalesPaper(ctx, req.(*UpdateSalesPaperRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EasService_SetSalesPaperStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSalesPaperStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EasServiceServer).SetSalesPaperStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eas_api.v1.EasService/SetSalesPaperStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EasServiceServer).SetSalesPaperStatus(ctx, req.(*SetSalesPaperStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EasService_DeleteSalesPaper_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSalesPaperRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EasServiceServer).DeleteSalesPaper(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eas_api.v1.EasService/DeleteSalesPaper",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EasServiceServer).DeleteSalesPaper(ctx, req.(*DeleteSalesPaperRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EasService_ServiceDesc is the grpc.ServiceDesc for EasService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EasService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "eas_api.v1.EasService",
	HandlerType: (*EasServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _EasService_Login_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _EasService_CreateUser_Handler,
		},
		{
			MethodName: "GetPageList",
			Handler:    _EasService_GetPageList_Handler,
		},
		{
			MethodName: "GetUserDetail",
			Handler:    _EasService_GetUserDetail_Handler,
		},
		{
			MethodName: "GetUserSelfDetail",
			Handler:    _EasService_GetUserSelfDetail_Handler,
		},
		{
			MethodName: "SetUserStatus",
			Handler:    _EasService_SetUserStatus_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _EasService_UpdateUser_Handler,
		},
		{
			MethodName: "UpdateUserSelf",
			Handler:    _EasService_UpdateUserSelf_Handler,
		},
		{
			MethodName: "ResetUserPassWord",
			Handler:    _EasService_ResetUserPassWord_Handler,
		},
		{
			MethodName: "UpdateUserPassWord",
			Handler:    _EasService_UpdateUserPassWord_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _EasService_DeleteUser_Handler,
		},
		{
			MethodName: "CreateSalesPaper",
			Handler:    _EasService_CreateSalesPaper_Handler,
		},
		{
			MethodName: "GetSalesPaperPageList",
			Handler:    _EasService_GetSalesPaperPageList_Handler,
		},
		{
			MethodName: "GetUsableSalesPaperPageList",
			Handler:    _EasService_GetUsableSalesPaperPageList_Handler,
		},
		{
			MethodName: "GetSalesPaperDetail",
			Handler:    _EasService_GetSalesPaperDetail_Handler,
		},
		{
			MethodName: "UpdateSalesPaper",
			Handler:    _EasService_UpdateSalesPaper_Handler,
		},
		{
			MethodName: "SetSalesPaperStatus",
			Handler:    _EasService_SetSalesPaperStatus_Handler,
		},
		{
			MethodName: "DeleteSalesPaper",
			Handler:    _EasService_DeleteSalesPaper_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "eas_api/v1/eas.proto",
}
