// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.3
// source: eas_api/v1/eas_examinee_models.proto

package v1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExamineeStatus int32

const (
	ExamineeStatus_ExamineeNotActive ExamineeStatus = 0 // 未激活
	ExamineeStatus_ExamineeActive    ExamineeStatus = 1 // 已激活
)

// Enum value maps for ExamineeStatus.
var (
	ExamineeStatus_name = map[int32]string{
		0: "ExamineeNotActive",
		1: "ExamineeActive",
	}
	ExamineeStatus_value = map[string]int32{
		"ExamineeNotActive": 0,
		"ExamineeActive":    1,
	}
)

func (x ExamineeStatus) Enum() *ExamineeStatus {
	p := new(ExamineeStatus)
	*p = x
	return p
}

func (x ExamineeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExamineeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_eas_api_v1_eas_examinee_models_proto_enumTypes[0].Descriptor()
}

func (ExamineeStatus) Type() protoreflect.EnumType {
	return &file_eas_api_v1_eas_examinee_models_proto_enumTypes[0]
}

func (x ExamineeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExamineeStatus.Descriptor instead.
func (ExamineeStatus) EnumDescriptor() ([]byte, []int) {
	return file_eas_api_v1_eas_examinee_models_proto_rawDescGZIP(), []int{0}
}

type SaveExamineeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExamineeData []*SaveExamineeData `protobuf:"bytes,1,rep,name=examinee_data,json=examinee_data,proto3" json:"examinee_data"`
}

func (x *SaveExamineeRequest) Reset() {
	*x = SaveExamineeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eas_api_v1_eas_examinee_models_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveExamineeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveExamineeRequest) ProtoMessage() {}

func (x *SaveExamineeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eas_api_v1_eas_examinee_models_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveExamineeRequest.ProtoReflect.Descriptor instead.
func (*SaveExamineeRequest) Descriptor() ([]byte, []int) {
	return file_eas_api_v1_eas_examinee_models_proto_rawDescGZIP(), []int{0}
}

func (x *SaveExamineeRequest) GetExamineeData() []*SaveExamineeData {
	if x != nil {
		return x.ExamineeData
	}
	return nil
}

type SaveExamineeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SaveExamineeResponse) Reset() {
	*x = SaveExamineeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eas_api_v1_eas_examinee_models_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveExamineeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveExamineeResponse) ProtoMessage() {}

func (x *SaveExamineeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eas_api_v1_eas_examinee_models_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveExamineeResponse.ProtoReflect.Descriptor instead.
func (*SaveExamineeResponse) Descriptor() ([]byte, []int) {
	return file_eas_api_v1_eas_examinee_models_proto_rawDescGZIP(), []int{1}
}

type SaveExamineeData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExamineeId string `protobuf:"bytes,1,opt,name=examinee_id,json=examinee_id,proto3" json:"examinee_id"`
	UserName   string `protobuf:"bytes,2,opt,name=user_name,json=user_name,proto3" json:"user_name"`
	Email      string `protobuf:"bytes,3,opt,name=email,json=email,proto3" json:"email"`
	Phone      string `protobuf:"bytes,4,opt,name=phone,json=phone,proto3" json:"phone"`
}

func (x *SaveExamineeData) Reset() {
	*x = SaveExamineeData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eas_api_v1_eas_examinee_models_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveExamineeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveExamineeData) ProtoMessage() {}

func (x *SaveExamineeData) ProtoReflect() protoreflect.Message {
	mi := &file_eas_api_v1_eas_examinee_models_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveExamineeData.ProtoReflect.Descriptor instead.
func (*SaveExamineeData) Descriptor() ([]byte, []int) {
	return file_eas_api_v1_eas_examinee_models_proto_rawDescGZIP(), []int{2}
}

func (x *SaveExamineeData) GetExamineeId() string {
	if x != nil {
		return x.ExamineeId
	}
	return ""
}

func (x *SaveExamineeData) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *SaveExamineeData) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SaveExamineeData) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type ExamineeData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExamineeId string         `protobuf:"bytes,1,opt,name=examinee_id,json=examinee_id,proto3" json:"examinee_id"`
	UserName   string         `protobuf:"bytes,2,opt,name=user_name,json=user_name,proto3" json:"user_name"`
	Status     ExamineeStatus `protobuf:"varint,3,opt,name=status,json=status,proto3,enum=eas_api.v1.ExamineeStatus" json:"status"`
	Email      string         `protobuf:"bytes,4,opt,name=email,json=email,proto3" json:"email"`
	Phone      string         `protobuf:"bytes,5,opt,name=phone,json=phone,proto3" json:"phone"`
	UpdatedAt  string         `protobuf:"bytes,6,opt,name=updated_at,json=updated_at,proto3" json:"updated_at"`
	UpdatedBy  string         `protobuf:"bytes,7,opt,name=updated_by,json=updated_by,proto3" json:"updated_by"`
}

func (x *ExamineeData) Reset() {
	*x = ExamineeData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eas_api_v1_eas_examinee_models_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExamineeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExamineeData) ProtoMessage() {}

func (x *ExamineeData) ProtoReflect() protoreflect.Message {
	mi := &file_eas_api_v1_eas_examinee_models_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExamineeData.ProtoReflect.Descriptor instead.
func (*ExamineeData) Descriptor() ([]byte, []int) {
	return file_eas_api_v1_eas_examinee_models_proto_rawDescGZIP(), []int{3}
}

func (x *ExamineeData) GetExamineeId() string {
	if x != nil {
		return x.ExamineeId
	}
	return ""
}

func (x *ExamineeData) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *ExamineeData) GetStatus() ExamineeStatus {
	if x != nil {
		return x.Status
	}
	return ExamineeStatus_ExamineeNotActive
}

func (x *ExamineeData) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ExamineeData) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *ExamineeData) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *ExamineeData) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

type GetExamineePageListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyWord   string `protobuf:"bytes,1,opt,name=key_word,json=key_word,proto3" json:"key_word"`
	PageIndex int32  `protobuf:"varint,2,opt,name=page_index,json=page_index,proto3" json:"page_index"`
	PageSize  int32  `protobuf:"varint,3,opt,name=page_size,json=page_size,proto3" json:"page_size"`
}

func (x *GetExamineePageListRequest) Reset() {
	*x = GetExamineePageListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eas_api_v1_eas_examinee_models_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetExamineePageListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExamineePageListRequest) ProtoMessage() {}

func (x *GetExamineePageListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eas_api_v1_eas_examinee_models_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExamineePageListRequest.ProtoReflect.Descriptor instead.
func (*GetExamineePageListRequest) Descriptor() ([]byte, []int) {
	return file_eas_api_v1_eas_examinee_models_proto_rawDescGZIP(), []int{4}
}

func (x *GetExamineePageListRequest) GetKeyWord() string {
	if x != nil {
		return x.KeyWord
	}
	return ""
}

func (x *GetExamineePageListRequest) GetPageIndex() int32 {
	if x != nil {
		return x.PageIndex
	}
	return 0
}

func (x *GetExamineePageListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetExamineePageListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExamineeData []*ExamineeData `protobuf:"bytes,1,rep,name=examinee_data,json=examinee_data,proto3" json:"examinee_data"`
	Total        int64           `protobuf:"varint,2,opt,name=total,json=total,proto3" json:"total"`
}

func (x *GetExamineePageListResponse) Reset() {
	*x = GetExamineePageListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eas_api_v1_eas_examinee_models_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetExamineePageListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExamineePageListResponse) ProtoMessage() {}

func (x *GetExamineePageListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eas_api_v1_eas_examinee_models_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExamineePageListResponse.ProtoReflect.Descriptor instead.
func (*GetExamineePageListResponse) Descriptor() ([]byte, []int) {
	return file_eas_api_v1_eas_examinee_models_proto_rawDescGZIP(), []int{5}
}

func (x *GetExamineePageListResponse) GetExamineeData() []*ExamineeData {
	if x != nil {
		return x.ExamineeData
	}
	return nil
}

func (x *GetExamineePageListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetExamineeDetailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExamineeId string `protobuf:"bytes,1,opt,name=examinee_id,json=examinee_id,proto3" json:"examinee_id"`
}

func (x *GetExamineeDetailRequest) Reset() {
	*x = GetExamineeDetailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eas_api_v1_eas_examinee_models_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetExamineeDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExamineeDetailRequest) ProtoMessage() {}

func (x *GetExamineeDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eas_api_v1_eas_examinee_models_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExamineeDetailRequest.ProtoReflect.Descriptor instead.
func (*GetExamineeDetailRequest) Descriptor() ([]byte, []int) {
	return file_eas_api_v1_eas_examinee_models_proto_rawDescGZIP(), []int{6}
}

func (x *GetExamineeDetailRequest) GetExamineeId() string {
	if x != nil {
		return x.ExamineeId
	}
	return ""
}

type GetExamineeDetailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExamineeData *ExamineeData `protobuf:"bytes,1,opt,name=examinee_data,json=examinee_data,proto3" json:"examinee_data"`
}

func (x *GetExamineeDetailResponse) Reset() {
	*x = GetExamineeDetailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eas_api_v1_eas_examinee_models_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetExamineeDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExamineeDetailResponse) ProtoMessage() {}

func (x *GetExamineeDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eas_api_v1_eas_examinee_models_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExamineeDetailResponse.ProtoReflect.Descriptor instead.
func (*GetExamineeDetailResponse) Descriptor() ([]byte, []int) {
	return file_eas_api_v1_eas_examinee_models_proto_rawDescGZIP(), []int{7}
}

func (x *GetExamineeDetailResponse) GetExamineeData() *ExamineeData {
	if x != nil {
		return x.ExamineeData
	}
	return nil
}

type UpdateExamineeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExamineeData *SaveExamineeData `protobuf:"bytes,1,opt,name=examinee_data,json=examinee_data,proto3" json:"examinee_data"`
}

func (x *UpdateExamineeRequest) Reset() {
	*x = UpdateExamineeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eas_api_v1_eas_examinee_models_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateExamineeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExamineeRequest) ProtoMessage() {}

func (x *UpdateExamineeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eas_api_v1_eas_examinee_models_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExamineeRequest.ProtoReflect.Descriptor instead.
func (*UpdateExamineeRequest) Descriptor() ([]byte, []int) {
	return file_eas_api_v1_eas_examinee_models_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateExamineeRequest) GetExamineeData() *SaveExamineeData {
	if x != nil {
		return x.ExamineeData
	}
	return nil
}

type UpdateExamineeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateExamineeResponse) Reset() {
	*x = UpdateExamineeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eas_api_v1_eas_examinee_models_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateExamineeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExamineeResponse) ProtoMessage() {}

func (x *UpdateExamineeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eas_api_v1_eas_examinee_models_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExamineeResponse.ProtoReflect.Descriptor instead.
func (*UpdateExamineeResponse) Descriptor() ([]byte, []int) {
	return file_eas_api_v1_eas_examinee_models_proto_rawDescGZIP(), []int{9}
}

type DeleteExamineeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExamineeId string `protobuf:"bytes,1,opt,name=examinee_id,json=examinee_id,proto3" json:"examinee_id"`
}

func (x *DeleteExamineeRequest) Reset() {
	*x = DeleteExamineeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eas_api_v1_eas_examinee_models_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteExamineeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExamineeRequest) ProtoMessage() {}

func (x *DeleteExamineeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eas_api_v1_eas_examinee_models_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExamineeRequest.ProtoReflect.Descriptor instead.
func (*DeleteExamineeRequest) Descriptor() ([]byte, []int) {
	return file_eas_api_v1_eas_examinee_models_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteExamineeRequest) GetExamineeId() string {
	if x != nil {
		return x.ExamineeId
	}
	return ""
}

type DeleteExamineeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteExamineeResponse) Reset() {
	*x = DeleteExamineeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eas_api_v1_eas_examinee_models_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteExamineeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExamineeResponse) ProtoMessage() {}

func (x *DeleteExamineeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eas_api_v1_eas_examinee_models_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExamineeResponse.ProtoReflect.Descriptor instead.
func (*DeleteExamineeResponse) Descriptor() ([]byte, []int) {
	return file_eas_api_v1_eas_examinee_models_proto_rawDescGZIP(), []int{11}
}

var File_eas_api_v1_eas_examinee_models_proto protoreflect.FileDescriptor

var file_eas_api_v1_eas_examinee_models_proto_rawDesc = []byte{
	0x0a, 0x24, 0x65, 0x61, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x61, 0x73,
	0x5f, 0x65, 0x78, 0x61, 0x6d, 0x69, 0x6e, 0x65, 0x65, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x65, 0x61, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e,
	0x76, 0x31, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x6f,
	0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x76, 0x32, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1b, 0x65, 0x61, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x65,
	0x61, 0x73, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x6d, 0x0a, 0x13, 0x53, 0x61, 0x76, 0x65, 0x45, 0x78, 0x61, 0x6d, 0x69, 0x6e, 0x65, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x56, 0x0a, 0x0d, 0x65, 0x78, 0x61, 0x6d, 0x69, 0x6e,
	0x65, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x65, 0x61, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x45,
	0x78, 0x61, 0x6d, 0x69, 0x6e, 0x65, 0x65, 0x44, 0x61, 0x74, 0x61, 0x42, 0x12, 0x92, 0x41, 0x0f,
	0x2a, 0x0d, 0x65, 0x78, 0x61, 0x6d, 0x69, 0x6e, 0x65, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x52,
	0x0d, 0x65, 0x78, 0x61, 0x6d, 0x69, 0x6e, 0x65, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x22, 0x16,
	0x0a, 0x14, 0x53, 0x61, 0x76, 0x65, 0x45, 0x78, 0x61, 0x6d, 0x69, 0x6e, 0x65, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xd6, 0x01, 0x0a, 0x10, 0x53, 0x61, 0x76, 0x65, 0x45,
	0x78, 0x61, 0x6d, 0x69, 0x6e, 0x65, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x32, 0x0a, 0x0b, 0x65,
	0x78, 0x61, 0x6d, 0x69, 0x6e, 0x65, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x10, 0x92, 0x41, 0x0d, 0x2a, 0x0b, 0x65, 0x78, 0x61, 0x6d, 0x69, 0x6e, 0x65, 0x65, 0x5f,
	0x69, 0x64, 0x52, 0x0b, 0x65, 0x78, 0x61, 0x6d, 0x69, 0x6e, 0x65, 0x65, 0x5f, 0x69, 0x64, 0x12,
	0x38, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x42, 0x1a, 0x92, 0x41, 0x17, 0x2a, 0x09, 0xe7, 0x94, 0xa8, 0xe6, 0x88, 0xb7, 0xe5,
	0x90, 0x8d, 0xd2, 0x01, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x09,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x29, 0x0a, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x13, 0x92, 0x41, 0x10, 0x2a, 0x06, 0xe9,
	0x82, 0xae, 0xe4, 0xbb, 0xb6, 0xd2, 0x01, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x12, 0x29, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x42, 0x13, 0x92, 0x41, 0x10, 0x2a, 0x06, 0xe7, 0x94, 0xb5, 0xe8, 0xaf, 0x9d,
	0xd2, 0x01, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x22,
	0xa5, 0x03, 0x0a, 0x0c, 0x45, 0x78, 0x61, 0x6d, 0x69, 0x6e, 0x65, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x32, 0x0a, 0x0b, 0x65, 0x78, 0x61, 0x6d, 0x69, 0x6e, 0x65, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x10, 0x92, 0x41, 0x0d, 0x2a, 0x0b, 0x65, 0x78, 0x61, 0x6d,
	0x69, 0x6e, 0x65, 0x65, 0x5f, 0x69, 0x64, 0x52, 0x0b, 0x65, 0x78, 0x61, 0x6d, 0x69, 0x6e, 0x65,
	0x65, 0x5f, 0x69, 0x64, 0x12, 0x38, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x1a, 0x92, 0x41, 0x17, 0x2a, 0x09, 0xe7, 0x94,
	0xa8, 0xe6, 0x88, 0xb7, 0xe5, 0x90, 0x8d, 0xd2, 0x01, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x62,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a,
	0x2e, 0x65, 0x61, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x61, 0x6d,
	0x69, 0x6e, 0x65, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x2e, 0x92, 0x41, 0x2b, 0x2a,
	0x20, 0xe7, 0x8a, 0xb6, 0xe6, 0x80, 0x81, 0xef, 0xbc, 0x9a, 0x30, 0xe6, 0x9c, 0xaa, 0xe6, 0xbf,
	0x80, 0xe6, 0xb4, 0xbb, 0xef, 0xbc, 0x8c, 0x31, 0xe5, 0xb7, 0xb2, 0xe6, 0xbf, 0x80, 0xe6, 0xb4,
	0xbb, 0xd2, 0x01, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x29, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x42, 0x13, 0x92, 0x41, 0x10, 0x2a, 0x06, 0xe9, 0x82, 0xae, 0xe4, 0xbb, 0xb6, 0xd2, 0x01,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x29, 0x0a,
	0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x42, 0x13, 0x92, 0x41,
	0x10, 0x2a, 0x06, 0xe7, 0x94, 0xb5, 0xe8, 0xaf, 0x9d, 0xd2, 0x01, 0x05, 0x70, 0x68, 0x6f, 0x6e,
	0x65, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x37, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x42, 0x17, 0x92, 0x41,
	0x14, 0x2a, 0x12, 0xe6, 0x9c, 0x80, 0xe5, 0x90, 0x8e, 0xe6, 0x9b, 0xb4, 0xe6, 0x96, 0xb0, 0xe6,
	0x97, 0xb6, 0xe9, 0x97, 0xb4, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x12, 0x34, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x42, 0x14, 0x92, 0x41, 0x11, 0x2a, 0x0f, 0xe6, 0x9c, 0x80, 0xe5,
	0x90, 0x8e, 0xe6, 0x9b, 0xb4, 0xe6, 0x96, 0xb0, 0xe4, 0xba, 0xba, 0x52, 0x0a, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x22, 0xad, 0x01, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x45,
	0x78, 0x61, 0x6d, 0x69, 0x6e, 0x65, 0x65, 0x50, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x08, 0x6b, 0x65, 0x79, 0x5f, 0x77, 0x6f,
	0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x11, 0x92, 0x41, 0x0e, 0x2a, 0x0c, 0xe9,
	0x82, 0xae, 0xe7, 0xae, 0xb1, 0xe6, 0x90, 0x9c, 0xe7, 0xb4, 0xa2, 0x52, 0x08, 0x6b, 0x65, 0x79,
	0x5f, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x2e, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x42, 0x0e, 0x92, 0x41, 0x0b, 0x2a, 0x06,
	0xe9, 0xa1, 0xb5, 0xe7, 0xa0, 0x81, 0x3a, 0x01, 0x31, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x65, 0x5f,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x30, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69,
	0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x42, 0x12, 0x92, 0x41, 0x0f, 0x2a, 0x09, 0xe6,
	0xaf, 0x8f, 0xe9, 0xa1, 0xb5, 0xe6, 0x95, 0xb0, 0x3a, 0x02, 0x31, 0x30, 0x52, 0x09, 0x70, 0x61,
	0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x93, 0x01, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x45,
	0x78, 0x61, 0x6d, 0x69, 0x6e, 0x65, 0x65, 0x50, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x51, 0x0a, 0x0d, 0x65, 0x78, 0x61, 0x6d, 0x69,
	0x6e, 0x65, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x65, 0x61, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x61, 0x6d,
	0x69, 0x6e, 0x65, 0x65, 0x44, 0x61, 0x74, 0x61, 0x42, 0x11, 0x92, 0x41, 0x0e, 0x2a, 0x0c, 0xe8,
	0x80, 0x83, 0xe7, 0x94, 0x9f, 0xe4, 0xbf, 0xa1, 0xe6, 0x81, 0xaf, 0x52, 0x0d, 0x65, 0x78, 0x61,
	0x6d, 0x69, 0x6e, 0x65, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x12, 0x21, 0x0a, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x42, 0x0b, 0x92, 0x41, 0x08, 0x2a, 0x06,
	0xe6, 0x80, 0xbb, 0xe6, 0x95, 0xb0, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x4e, 0x0a,
	0x18, 0x47, 0x65, 0x74, 0x45, 0x78, 0x61, 0x6d, 0x69, 0x6e, 0x65, 0x65, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x0b, 0x65, 0x78, 0x61,
	0x6d, 0x69, 0x6e, 0x65, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x10,
	0x92, 0x41, 0x0d, 0x2a, 0x0b, 0x65, 0x78, 0x61, 0x6d, 0x69, 0x6e, 0x65, 0x65, 0x5f, 0x69, 0x64,
	0x52, 0x0b, 0x65, 0x78, 0x61, 0x6d, 0x69, 0x6e, 0x65, 0x65, 0x5f, 0x69, 0x64, 0x22, 0x6e, 0x0a,
	0x19, 0x47, 0x65, 0x74, 0x45, 0x78, 0x61, 0x6d, 0x69, 0x6e, 0x65, 0x65, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x51, 0x0a, 0x0d, 0x65, 0x78,
	0x61, 0x6d, 0x69, 0x6e, 0x65, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x65, 0x61, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x45,
	0x78, 0x61, 0x6d, 0x69, 0x6e, 0x65, 0x65, 0x44, 0x61, 0x74, 0x61, 0x42, 0x11, 0x92, 0x41, 0x0e,
	0x2a, 0x0c, 0xe8, 0x80, 0x83, 0xe7, 0x94, 0x9f, 0xe4, 0xbf, 0xa1, 0xe6, 0x81, 0xaf, 0x52, 0x0d,
	0x65, 0x78, 0x61, 0x6d, 0x69, 0x6e, 0x65, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x22, 0x6f, 0x0a,
	0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x78, 0x61, 0x6d, 0x69, 0x6e, 0x65, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x56, 0x0a, 0x0d, 0x65, 0x78, 0x61, 0x6d, 0x69, 0x6e,
	0x65, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x65, 0x61, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x45,
	0x78, 0x61, 0x6d, 0x69, 0x6e, 0x65, 0x65, 0x44, 0x61, 0x74, 0x61, 0x42, 0x12, 0x92, 0x41, 0x0f,
	0x2a, 0x0d, 0x65, 0x78, 0x61, 0x6d, 0x69, 0x6e, 0x65, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x52,
	0x0d, 0x65, 0x78, 0x61, 0x6d, 0x69, 0x6e, 0x65, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x22, 0x18,
	0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x78, 0x61, 0x6d, 0x69, 0x6e, 0x65, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x4b, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x45, 0x78, 0x61, 0x6d, 0x69, 0x6e, 0x65, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x32, 0x0a, 0x0b, 0x65, 0x78, 0x61, 0x6d, 0x69, 0x6e, 0x65, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x10, 0x92, 0x41, 0x0d, 0x2a, 0x0b, 0x65, 0x78, 0x61,
	0x6d, 0x69, 0x6e, 0x65, 0x65, 0x5f, 0x69, 0x64, 0x52, 0x0b, 0x65, 0x78, 0x61, 0x6d, 0x69, 0x6e,
	0x65, 0x65, 0x5f, 0x69, 0x64, 0x22, 0x18, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45,
	0x78, 0x61, 0x6d, 0x69, 0x6e, 0x65, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2a,
	0x3b, 0x0a, 0x0e, 0x45, 0x78, 0x61, 0x6d, 0x69, 0x6e, 0x65, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x15, 0x0a, 0x11, 0x45, 0x78, 0x61, 0x6d, 0x69, 0x6e, 0x65, 0x65, 0x4e, 0x6f, 0x74,
	0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x45, 0x78, 0x61, 0x6d,
	0x69, 0x6e, 0x65, 0x65, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x10, 0x01, 0x42, 0x13, 0x5a, 0x11,
	0x65, 0x61, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x3b, 0x76,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_eas_api_v1_eas_examinee_models_proto_rawDescOnce sync.Once
	file_eas_api_v1_eas_examinee_models_proto_rawDescData = file_eas_api_v1_eas_examinee_models_proto_rawDesc
)

func file_eas_api_v1_eas_examinee_models_proto_rawDescGZIP() []byte {
	file_eas_api_v1_eas_examinee_models_proto_rawDescOnce.Do(func() {
		file_eas_api_v1_eas_examinee_models_proto_rawDescData = protoimpl.X.CompressGZIP(file_eas_api_v1_eas_examinee_models_proto_rawDescData)
	})
	return file_eas_api_v1_eas_examinee_models_proto_rawDescData
}

var file_eas_api_v1_eas_examinee_models_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_eas_api_v1_eas_examinee_models_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_eas_api_v1_eas_examinee_models_proto_goTypes = []interface{}{
	(ExamineeStatus)(0),                 // 0: eas_api.v1.ExamineeStatus
	(*SaveExamineeRequest)(nil),         // 1: eas_api.v1.SaveExamineeRequest
	(*SaveExamineeResponse)(nil),        // 2: eas_api.v1.SaveExamineeResponse
	(*SaveExamineeData)(nil),            // 3: eas_api.v1.SaveExamineeData
	(*ExamineeData)(nil),                // 4: eas_api.v1.ExamineeData
	(*GetExamineePageListRequest)(nil),  // 5: eas_api.v1.GetExamineePageListRequest
	(*GetExamineePageListResponse)(nil), // 6: eas_api.v1.GetExamineePageListResponse
	(*GetExamineeDetailRequest)(nil),    // 7: eas_api.v1.GetExamineeDetailRequest
	(*GetExamineeDetailResponse)(nil),   // 8: eas_api.v1.GetExamineeDetailResponse
	(*UpdateExamineeRequest)(nil),       // 9: eas_api.v1.UpdateExamineeRequest
	(*UpdateExamineeResponse)(nil),      // 10: eas_api.v1.UpdateExamineeResponse
	(*DeleteExamineeRequest)(nil),       // 11: eas_api.v1.DeleteExamineeRequest
	(*DeleteExamineeResponse)(nil),      // 12: eas_api.v1.DeleteExamineeResponse
}
var file_eas_api_v1_eas_examinee_models_proto_depIdxs = []int32{
	3, // 0: eas_api.v1.SaveExamineeRequest.examinee_data:type_name -> eas_api.v1.SaveExamineeData
	0, // 1: eas_api.v1.ExamineeData.status:type_name -> eas_api.v1.ExamineeStatus
	4, // 2: eas_api.v1.GetExamineePageListResponse.examinee_data:type_name -> eas_api.v1.ExamineeData
	4, // 3: eas_api.v1.GetExamineeDetailResponse.examinee_data:type_name -> eas_api.v1.ExamineeData
	3, // 4: eas_api.v1.UpdateExamineeRequest.examinee_data:type_name -> eas_api.v1.SaveExamineeData
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_eas_api_v1_eas_examinee_models_proto_init() }
func file_eas_api_v1_eas_examinee_models_proto_init() {
	if File_eas_api_v1_eas_examinee_models_proto != nil {
		return
	}
	file_eas_api_v1_eas_models_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_eas_api_v1_eas_examinee_models_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveExamineeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eas_api_v1_eas_examinee_models_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveExamineeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eas_api_v1_eas_examinee_models_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveExamineeData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eas_api_v1_eas_examinee_models_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExamineeData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eas_api_v1_eas_examinee_models_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetExamineePageListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eas_api_v1_eas_examinee_models_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetExamineePageListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eas_api_v1_eas_examinee_models_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetExamineeDetailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eas_api_v1_eas_examinee_models_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetExamineeDetailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eas_api_v1_eas_examinee_models_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateExamineeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eas_api_v1_eas_examinee_models_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateExamineeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eas_api_v1_eas_examinee_models_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteExamineeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eas_api_v1_eas_examinee_models_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteExamineeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_eas_api_v1_eas_examinee_models_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_eas_api_v1_eas_examinee_models_proto_goTypes,
		DependencyIndexes: file_eas_api_v1_eas_examinee_models_proto_depIdxs,
		EnumInfos:         file_eas_api_v1_eas_examinee_models_proto_enumTypes,
		MessageInfos:      file_eas_api_v1_eas_examinee_models_proto_msgTypes,
	}.Build()
	File_eas_api_v1_eas_examinee_models_proto = out.File
	file_eas_api_v1_eas_examinee_models_proto_rawDesc = nil
	file_eas_api_v1_eas_examinee_models_proto_goTypes = nil
	file_eas_api_v1_eas_examinee_models_proto_depIdxs = nil
}
