// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameExaminee = "examinee"

// Examinee 正式参加测评的考生
type Examinee struct {
	ID           string         `gorm:"column:id;primaryKey;comment:主键（Guid）" json:"id"`                                     // 主键（Guid）
	SalesPaperID string         `gorm:"column:sales_paper_id;not null;comment:SalesPaper表的外键" json:"sales_paper_id"`         // SalesPaper表的外键
	ExamName     string         `gorm:"column:exam_name;not null;comment:考试名称" json:"exam_name"`                             // 考试名称
	ExamineeID   string         `gorm:"column:examinee_id;not null;comment:关联考生ID" json:"examinee_id"`                       // 关联考生ID
	EmailStatus  int32          `gorm:"column:email_status;not null;default:1;comment:邮件状态：1.未发送，2.已发送" json:"email_status"` // 邮件状态：1.未发送，2.已发送
	CreatedAt    time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt    time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	CreatedBy    string         `gorm:"column:created_by;not null;comment:创建人标识" json:"created_by"`                          // 创建人标识
	UpdatedBy    string         `gorm:"column:updated_by;not null;comment:更新人标识" json:"updated_by"`                          // 更新人标识
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;comment:逻辑删除时间" json:"deleted_at"`                                  // 逻辑删除时间
}

// TableName Examinee's table name
func (*Examinee) TableName() string {
	return TableNameExaminee
}
